services:
  db:
    image: postgres:15
    container_name: sonar-postgres-vitalcare
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - ci-net

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqubeVitalcare
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    networks:
      - ci-net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkinsVitalcare
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - sonarqube
    networks:
      - ci-net

volumes:
  jenkins_home:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  sonar_db_data:

networks:
  ci-net:
    driver: bridge
